### ISSUE TITLE
keep matching highlighted even after selected

### ISSUE THREAD

**Issue by hawsome** [atom-minimap/minimap-highlight-selected#10]
After toggling a matching highlighted string (with `cmd + d`) it disappears from the minimap.

**Comment by abe33** [comment]
Sorry, but I can't reproduce this, what versions (atom, minimap, highlight-selected and minimap-highlight-selected) are you using?

**Comment by hawsome** [comment]
Sublime on top, Atom on bottom. Pay attention to the selected text in the mini maps. Sublime keeps the selected highlighted at a slightly lower opacity, Atom's just disappears altogether when selected.

![select2](https://cloud.githubusercontent.com/assets/567126/7809600/6b9c1918-0350-11e5-9612-46c571e46489.gif)

**Comment by abe33** [comment]
You didn't answer my question regarding the various versions (atom & the involved packages).

I think the problems come from the following setting in `highlight-selected`: 

![settings_-__users_cedric_github_pigments_-_atom](https://cloud.githubusercontent.com/assets/247140/7812509/3baef56e-03b3-11e5-88bd-c508a7d1bcbd.png)

It looks like it removes the selection in `highlight-selected` and so `minimap-highlight-selected` gets the same behavior by extension. I'll see how I can overwrite this in the minimap plugin.

**Comment by hawsome** [comment]
Whoops, here ya go!
![screen shot 2015-05-26 at 8 39 11 am](https://cloud.githubusercontent.com/assets/567126/7816358/bce57c9c-0382-11e5-9806-2d50517f416f.png)

**Comment by abe33** [comment]
Yes, I agree. I don't know when I'll have the time to look at that, but I'll definitely considering adding that feature.
