### ISSUE TITLE
Error in debugging console

### ISSUE THREAD

**Issue by rugk** [atom-minimap/minimap-highlight-selected#15]
After installing this with a few other minimap packages I got the following error every restart (Sorry I couldn't screenshot it all):

![afterenabling](https://cloud.githubusercontent.com/assets/11966684/9385184/4b04c404-4755-11e5-96e1-5dbbf8098891.PNG)

**Comment by rugk** [comment]
Interestingly this issue occurred **after** I disabled the add-on. After I uninstalled it the error message was gone.

**Comment by rugk** [comment]
Okay, mabe the issue could be that I had the package 'minimap-display-selection' installed too.

**Comment by rugk** [comment]
Yes without 'minimap-display-selection' and only 'minimap-highlight-selection' it does not appear.

**Comment by abe33** [comment]
Have you installed the [highlight-selected package](http://atom.io/packages/highlight-selected)? This plugin is mostly a binding between the package and the minimap.

**Comment by rugk** [comment]
Ah, no that was the problem. Thanks, didn't knew that.
