### ISSUE TITLE
Highlight issue with php

### ISSUE THREAD

**Issue by aleksus** [atom-minimap/minimap-highlight-selected#19]
When I select a php variable $var, which is red by default, It will not popup on minimap. I suppose some regular expression needs tuning. Thanks for the awesome extension btw.

**Comment by abe33** [comment]
Are matches highlighted in the text editor? Because, this package only reuse markers created by `highlight-selected` in the text editor.

**Comment by aleksus** [comment]
Yes, they are.

**Comment by richrace** [comment]
Could be due to me doing this dirty hack: https://github.com/richrace/highlight-selected/blob/master/lib/highlighted-area-view.coffee#L103-L105

**Comment by abe33** [comment]
@richrace Probably, ideally I would like to have #9 solved so that I no longer need to maintain a fork of the view in this package, did you had time to look at that?

**Comment by sharifzadesina** [comment]
any fix for this problem?!
