### ISSUE TITLE
Changing color does not appear to work

### ISSUE THREAD

**Issue by GradyD** [atom-minimap/minimap-highlight-selected#22]
I have added to my styles.less the following code:

```
 /* The rule for selected highlights */
 .minimap .highlight-selected.selected {
   background: red !important;
 }
```

But my highlight color is not being applied. I tried to inspect the minimap but since it comes in as a canvas I was not able to determine the needed CSS. Can you please confirm that the above is the correct selectors?

**Comment by abe33** [comment]
Hmm, I've tried your sample in my user stylesheet and it worked. Are you putting that in a scope like `atom-text-editor`? Because it should just be a root rule.

**Comment by GradyD** [comment]
Hey,

I do not have this in any scope, it is at the top of my style sheet and I do not have any other styles in my sheet, ![image](https://cloud.githubusercontent.com/assets/994964/15361653/61f4a146-1ce0-11e6-8256-4e289049fe06.png)

I'm using atom version 1.7.3 on windows 7. I'm using Atom Material as my UI and Syntax theme. What I'm seeing is, 
![image](https://cloud.githubusercontent.com/assets/994964/15361704/978d81b0-1ce0-11e6-9a71-28d73318ed3b.png)

The file with the code is not saved if that makes a difference. The only reason I want to change it is because it is difficult to see with this theme. If I switch to Atom Dark for my UI theme it is much easier to read, 
![image](https://cloud.githubusercontent.com/assets/994964/15361734/bfbdfb6a-1ce0-11e6-87c2-61e5a7296bf5.png)

Any idea on how I can make this work or what could be causing the issue?

**Comment by abe33** [comment]
No problem, glad it now works for you :)
