### ISSUE TITLE
words beginning with $ are not highlighted in minimap

### ISSUE THREAD

**Issue by pmachart** [atom-minimap/minimap-highlight-selected#23]
when i select (double click or shift + arrow) a word beginning with a $ symbol, package "highlight-selected" does its job in the editor, but in the minimap, only the current selection is highlighted, not other occurences.

it looks like a duplicate of #19 but it doesn't only apply to php syntax

**Comment by UziTech** [comment]
This seems to be fixed now. If it is still an issue feel free to reopen it or start a new issue.
