### ISSUE TITLE
Nothing is highlighted on Minimap

### ISSUE THREAD

**Issue by caiolouro** [atom-minimap/minimap-highlight-selected#24]
Seems to be not working at all for me. I'm using OS X El Capitan, Atom 1.10.2 and minimap-highlight-selected 4.4.0.

**Comment by abe33** [comment]
Hi @caiolouro, do you also have the [`highlight-selected` package](https://atom.io/packages/highlight-selected) installed?

**Comment by caiolouro** [comment]
Hey, Cédric. No, I didn't, now that I have it's working fine. Thanks for pointing it out.

I thought Atom had some kind of dependency control for packages...
