### ISSUE TITLE
Only works when "Display Plugin Control" is selected

### ISSUE THREAD

**Issue by k4nar** [atom-minimap/minimap-highlight-selected#3]
This plugin is only working if "Display Plugin Control" is checked in Minimap's configuration. I don't know if it's a bug from this plugin or from Minimap as I don't have any other plugin.

**Comment by k4nar** [comment]
I can reproduce this issue with Atom 0.177.0, minimap 4.1.0, minimap-highlight-selected 4.0.0 and highlight-select 0.8.0.

**Comment by abe33** [comment]
There must some other thing, I just doesn't see why this setting would cause that behavior, I've tried this several times and couldn't reproduce it. I'll check that again later.

**Comment by k4nar** [comment]
Well the plugin wasn't working since a few days or so, so I tried to reactivate this option and it fixed it.
Sorry I can't think of any other relevant information.

BTW, what does the "V4 Preview" button do now that Minimap v4 has been released ?

**Comment by abe33** [comment]
The setting should not remain as it was removed from the config object with v4. It's because it's still referenced in your `config.json`. I haven't looked if there's a preferable way to remove settings in a graceful manner so that the old settings doesn't show up after being removed.

**Comment by 190n** [comment]
I can also reproduce this with atom 0.177 on Ubuntu. Minimap 4.1.0, Minimap Highlight Selected 4.0.0, Highlight Selected 0.7.0.

**Comment by fundon** [comment]
If there is still a `V4 Preview` button, you can remove it from `config.json`.

I think toggling the "Display Plugin Controls" that just `hide`/`show` UI. **The behavior is ok**.

If you want to disable/enable the plugin, you should toggle this.
![screen shot 2015-02-23 at 1 21 41 am](https://cloud.githubusercontent.com/assets/27926/6319539/675f944a-bafa-11e4-8d8d-56553cafc033.png)

**Comment by durz** [comment]
These are my steps to reproduce this, however, I don't know what exactly makes minimap highlighting stop working.

1. Minimap highlighting stopped working
2. Went to the settings for the Minimap package
3. **Ticked** the box for "Display Plugin Controls"
4. Restarted Atom
5. Minimap highlighting started to work again
6. Went to the settings for the Minimap package
7. **Unticked** the box for "Display Plugin Controls"
8. Restarted Atom
9. Minimap highlighting still works

**Comment by richrace** [comment]
I recently updated the highlight select package which could have caused this. 

Richard Race
