### ISSUE TITLE
Occurance highlights "bleed in" from other panes

### ISSUE THREAD

**Issue by eilamg** [atom-minimap/minimap-highlight-selected#32]
When working in split-pane mode, highlights from neighboring panes are erroneously marked in the minimap for the current pane.

As an example (the right pane is the active one):
![splitpane](https://cloud.githubusercontent.com/assets/4570254/22212806/b08e7f14-e19a-11e6-821c-cde6cb263210.png)

Cheers

**Comment by richrace** [comment]
Thanks. Hadn't noticed that. Also, need to figure out how to access any Minimap for any active Pane.

https://github.com/richrace/highlight-selected/pull/126

**Comment by giannisp** [comment]
You can quickly fix this by disabling "Highlight In Panes" (Highlight selection in another panes) from the `highlight-selected` settings. It's not really useful as a feature anyway.

**Comment by awilkins** [comment]
This is a "workaround" rather than a fix - and I disagree, there are syntaxes where scope is not limited to one file - e.g. Terraform, where you declare a resource and it's scoped to a whole folder. It's useful to be able to open multiple files and see all the locations where that resource is mentioned.

**Comment by akukuq** [comment]
@awilkins, please reconsider if this issue should really be marked as "Closed".

The problem reported here is not that selections are highlighted in other panes (as pointed out, this is intended and can be switched off in the settings of highlight-selected package), but rather that highlights from other panes are displayed in the minimap of the currently selected pane. This is a bit tricky to explain in words, but perhaps the screenshots below will be helpful. (Please look closely at the minimaps.)

### No selection:
![image](https://cloud.githubusercontent.com/assets/25489199/23366749/2d70ea7a-fd08-11e6-8b77-8710bf5dc377.png)
All seems in order here.

### "XYZ" selected and left pane active:
![image](https://cloud.githubusercontent.com/assets/25489199/23366801/5b4f4838-fd08-11e6-8589-9d4bf94f011d.png)
In this screenshot we see that in addition to the three occurrences of "XYZ" in the left file, the "XYZ" from the right file is also highlighted in the minimap of the left file -- even though at this position the left file  contans "ABC". Moreover, this fourth highlight is *not* shown in the right file's minimap, where it belongs.

### "XYZ" selected and right pane active:
![image](https://cloud.githubusercontent.com/assets/25489199/23366831/7387ba0c-fd08-11e6-9af2-d2e4877a9f1f.png)
As in the previous case, highlights from the other file are shown in the current file's minimap. Additionally, the last"XYZ" occurrence in the left file is not highlighted at all, but this seems to be a separate bug that should be reported to highlight-selected package.

### Issue is not consistent
This problem does not manifest itself consistently. While making the above three screenshots, I observed that if you create a third pane with a third file, the problem disappears, even after the third pane is closed. This I don't understand at all ;)

**Comment by richrace** [comment]
This has been fixed in `highlight-selected` just waiting for the merge request #39 to be merged.
