### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by Eucodex** [atom-minimap/minimap-highlight-selected#35]
I use Atom 1.14.3 x64 and installed minimap 4.26.8 and minimap-highlight-selected 4.5.0.
Minimap works correctly, but highlight doesn't work. I read the issues, but cannot solve my problems. There is no effect of "Display Plugin Control" settings.

**Comment by richrace** [comment]
You need to have https://atom.io/packages/highlight-selected installed.
