### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by GuidoS** [atom-minimap/minimap-highlight-selected#37]
I have worked with this plugin in the past and have been really happy with it.

I recently installed i on my machine and it is not working and I am not sure why.

I am not sure how to debug this issue. Here is my current setup:

macOS@10.12.3
atom@1.14.4
├── atom-beautify@0.29.17
├── git-plus@7.3.3
├── linter@1.11.23
├── linter-pep8@1.3.2
├── linter-pycodestyle@2.0.0
├── minimap@4.26.8
├── minimap-highlight-selected@4.5.0
├── script@3.14.1
└── tabs-to-spaces@1.0.3

**Comment by gaabs** [comment]
You need to also download the [Highlight Selected](https://github.com/richrace/highlight-selected) package. Did you try with it?

**Comment by GuidoS** [comment]
@gaabs thank you, that worked for me... but did that used to be pushed ... is there documentation about needing this that I missed?

**Comment by hoodsy** [comment]
Have both plugins and have restarted Atom, but I'm not getting any highlights

**Comment by GuidoS** [comment]
dropping this issue
