### ISSUE TITLE
Highlight doesn't work after last update

### ISSUE THREAD

**Issue by sintylapse** [atom-minimap/minimap-highlight-selected#41]
It doesn't show highlighted words on the minimap

**Comment by richrace** [comment]
You do have https://atom.io/packages/highlight-selected installed Version 0.13.1? 

If so, does it work after you restart Atom?

**Comment by sintylapse** [comment]
It seems, I have an older version of Atom, but Atom doesn't propose to update itself
 
![untitled1](https://cloud.githubusercontent.com/assets/12295016/25277871/235d941e-26a9-11e7-9f76-6347dad0c73c.png)

**Comment by sintylapse** [comment]
Okay, I have installed 0.13.1 version somehow, so it works now, thanks
