### ISSUE TITLE
Not working for Windows?

### ISSUE THREAD

**Issue by FormBurden** [atom-minimap/minimap-highlight-selected#44]
So I have both installed and working. The Highlight addon works fine, but the minimap doesn't even show up. I tried searching and doing everything I can find on the issue. But it seems that it is not working for Windows. 

Atom: 1.22.1 x64 
Windows 10

Any other info you need, let me know.

**Comment by richrace** [comment]
What are your installed packages?

**Comment by gnessou91** [comment]
Hello, I have the same issue. I installed both hightlight-selected and minimap-hightlight-selected on Windows and the minimap doesn't show up. 
I also installed a community package : r-syntax.
Any idea ? Thanks
