### ISSUE TITLE
Dependencies do not install

### ISSUE THREAD

**Issue by harmonicus** [atom-minimap/minimap-highlight-selected#52]
Hey, after installing minimap-highlight-selected,
system ask me if i want to install dependencies,
i say YES for sure!

but nothings happends afterwards,
and the highlighting DO NOT WORK :/

no open bugs whatsoever are reported

every time after rebooting, it ask me again, i want to install dependencies
thanks

**Comment by UziTech** [comment]
does it work after installing [minimap](https://atom.io/packages/minimap) and [highlight-selected](https://atom.io/packages/highlight-selected) manually and restarting Atom?

**Comment by harmonicus** [comment]
That is exactly what i have

**Comment by UziTech** [comment]
Are those packages already installed? can you install them manually instead of through the notification?

**Comment by UziTech** [comment]
I order to actually see if this is an issue with minimap-highlight-selected I will need to know the following information:

- OS version
- Atom version
- APM version
- Other packages that you have installed
- Any errors in developer tools (View -> Developer -> Toggle Developer Tools)

**Comment by harmonicus** [comment]
What are the other dependencies?
I would even install them manually, but i do not have a list
 
 
Other packages
terminus by bus-stop
autocomplete-python by autocomplete-python
file-icons by file-icons
linte by steelbrain
linter-flake8 by atomlinter
minimap by atom-minimap
minimap-git-diff by j.w.
minimap-highlight-selected by j.w.
python-autopep8 by markbaas
script by rgbkrk

OS
MX/Debian Linux

Atom Version
1.53.0

$ apm -v
apm  2.5.2
npm  6.14.8
node 12.4.0 x64
atom 1.53.0
python 2.7.16
git 2.20.1


Any errors in developer tools (View -> Developer -> Toggle Developer Tools)
i dont see anything specific beside 1 Warning

/usr/share/atom/resources/app.asar/src/text-editor-element.js:357 [Deprecation] document.registerElement is deprecated and will be removed in M80, around February 2020. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.
(anonymous) @ /usr/share/atom/resources/app.asar/src/text-editor-element.js:357 




Thanks

**Comment by UziTech** [comment]
I listed the dependencies above

> does it work after installing [minimap](https://atom.io/packages/minimap) and [highlight-selected](https://atom.io/packages/highlight-selected) manually and restarting Atom?

Can you provide screenshots or a video/gif of what you are doing? I don't get how it can ask if you want to download the dependencies without giving you a list of the dependencies.

**Comment by harmonicus** [comment]
aaa,
ok name of the dependency and name of the package were very similar, that i lost it when in was in front of my eyes.
Now i've manually installed the dependency 
highlight-selected by richrace
and all is good,
thank you for opening my eyes and sorry for disturbing ;)

**Comment by Darpra27** [comment]
how did you manually install the dependency?  I have the same problem, but I don't know how to manually install a dependency

**Comment by UziTech** [comment]
go [here](https://atom.io/packages/minimap) and [here](https://atom.io/packages/highlight-selected) and click install
