### ISSUE TITLE
Dependencies do not install

### ISSUE THREAD

**Issue by Darpra27** [atom-minimap/minimap-highlight-selected#62]
I have the same issue than [this](https://github.com/atom-minimap/minimap-highlight-selected/issues/52) post and there some said that I have to manually install the dependency, but I don't know how to do it. Can someone tell me how? I tried to install it from the notification but it doesn't do anything

**Comment by UziTech** [comment]
go [here](https://atom.io/packages/minimap) and [here](https://atom.io/packages/highlight-selected) and click install
