### ISSUE TITLE
Should Highlight Selected Package have an API?

### ISSUE THREAD

**Issue by richrace** [atom-minimap/minimap-highlight-selected#9]
Would this be better than the current implementation and help with minimising errors that occur for when I updated the package?

If so what would you need?

**Comment by abe33** [comment]
Hi @richrace, that would be great indeed!

I've also seen some people proposing to merge this feature into `find-and-replace`, what's the status about that proposal?

**Comment by richrace** [comment]
Yea that's the plan. Haven't really looked in depth about it in a while as I've been a bit busy.

But I've started the process again. First step was removing the `space-pen-views` and having it as a view file, which this PR will solve: https://github.com/richrace/highlight-selected/pull/60

Now it's on to looking at the `find-and-replace` package and go from there.

So if it were to merge in with `find-and-replace` or stay by itself, should the package contain `minimap` plugin or leave it separated? If to leave it separated what does this plugin need to work?

**Comment by abe33** [comment]
As we already have a `minimap-find-and-replace` plugin as well, I think we should just let the minimap plugin handle this new `find-and-replace` feature in the case you merge it in it. Core packages shouldn't care about the minimap (as it's not a core package). 

If it stay separated, all I need is an access to a model that exposes a few events so that I can know when markers get changed to update the minimap decorations.

**Comment by richrace** [comment]
Ok. I think I'll implement the API anyway as I might be needed with the `find-and-replace` package anyway. 

I'll add some issues to the `highlight-selected` package to keep you (and everyone) up-to-date with the progress.

**Comment by abe33** [comment]
Great!

I believe this feature could be part of the find model, so in that case it's just a matter of listening for a few new events in the plugin. Let me know if you need anything.

**Comment by richrace** [comment]
Forgot to let you know that I have added the API and has been released.

**Comment by abe33** [comment]
@richrace BTW I can't recall if I mentioned my issue with markers destroyed when a match is selected? Did it ring a bell?

**Comment by richrace** [comment]
Just looked back at this: https://github.com/atom-minimap/minimap-highlight-selected/pull/12

So when `hideHighlightOnSelectedWord` is set `minimap` would still show them. If that's the case I'll have a look at changing how the `onDidAddMarker` event gets fired.

**Comment by abe33** [comment]
Yeah that's the one! :) I was looking in highlight-selected issues.

IMO, maybe a solution would be to either use a different class for the decoration in the text editor to hide them when selected or to destroy the decorations and leaving the markers intact.

Do you think it's feasible on your end?

**Comment by richrace** [comment]
This has been added and the branch https://github.com/atom-minimap/minimap-highlight-selected/tree/feature-highlight-selected-api needs to be merged in.
