### ISSUE TITLE
Dependencies don't install

### ISSUE THREAD

**Issue by Krinkle** [atom-minimap/minimap-highlight-selected#90]
I used this for several years without issue. Yesterday it stopped working for some reason out of the blue, possibly due to an Atom Editor update.

In the plugin manager, I re-enabled `minimap-highlight-selected` and it prompted to install `highlight-selected` (I'm pretty sure minimap and highlight-selected have been installed for years, but it seems highlight-selected somehow dissappeared yesterday, hence this prompt).

![capture](https://user-images.githubusercontent.com/156867/116178388-6375a580-a70d-11eb-959b-332f3cd14d1f.png)

But, pressing Yes, does not do anything. After a restart, the same thing keeps happening. I worked around it by manually installing it, but as reported twice before (https://github.com/atom-minimap/minimap-highlight-selected/issues/52, https://github.com/atom-minimap/minimap-highlight-selected/issues/62) there is a real problem here. Perhaps it is an upstream problem, but I have only seen it affect this plugin. I appreciate this plugin as-is and thank you for providing it. This is a small and easy hurdle to overcome, but it is likely to come up again and again for people, so if there's anything you can do or any question I can answer, let me know.

* Atom 1.56.0
* macOS 10.15

**Comment by UziTech** [comment]
I still can't recreate this issue. When I uninstalled `highlight-selected` And restarted Atom I got the notification above then clicked "Yes" And it installed fine with the following notifications:

![image](https://user-images.githubusercontent.com/97994/116180053-ee3eac00-a6dd-11eb-8473-8c11ba628233.png)

![image](https://user-images.githubusercontent.com/97994/116180059-f0086f80-a6dd-11eb-9988-b246961a546b.png)

The only way to solve this issue is to find someone who can recreate the issue and can debug it.

**Comment by Krinkle** [comment]
@UziTech I can reliably reproduce it, and did so numerous times before filing the issue. I can still reproduce it now as well.

1. Uninstall `highlight-selected`.
2. Disable but keep `minimap-highlight-selected`.
3. Restart Atom.
4. Enable `minimap-highlight-selected`, press "Yes" for installing `highlight-selected`.
5. Observe the button changing from "Enable" to "Disable" (as if it is now enabled), but the dependency has not been installed, nothing else happened on-screen, and in text files, the functionality remains absent.

| ![a](https://user-images.githubusercontent.com/156867/116323394-cae73000-a7b5-11eb-9661-e6b05a85edc7.png) | ![b](https://user-images.githubusercontent.com/156867/116323398-cde22080-a7b5-11eb-9fa9-73ace19c520c.png) | ![c](https://user-images.githubusercontent.com/156867/116323400-ce7ab700-a7b5-11eb-889e-fb3b0ea31466.png) | ![d](https://user-images.githubusercontent.com/156867/116323401-cf134d80-a7b5-11eb-81e9-76f7008199a7.png)
|--|--|--|--
| | | |

**Comment by UziTech** [comment]
Can you debug it? it must be specific to your setup since it works when I try it.

**Comment by UziTech** [comment]
This package uses [`atom-package-deps`](https://github.com/steelbrain/package-deps) to install the dependencies. You can find the code for this package in `~/.atom/packages/minimap-highlight-selected`.

**Comment by Krinkle** [comment]
OK. I'll try! I have not specifically worked on Atom or Atom plugins before, however.

I opened the Electron/Chrome's Developer Tools earlier, but as shown above nothing was logged during these interactions. If there is a debug mode of sorts you'd like me to enable or to inspect any particular function, let me know.

Here's some things that may be of use:

<details><summary><code>ls -halF ~/.atom/packages/minimap-highlight-selected/</code></summary>

```
~/.atom/packages/minimap-highlight-selected
$ l
total 412K
drwxr-xr-x 16 krinkle staff  512 Mar 17 18:34 ./
drwxr-xr-x 13 krinkle staff  416 Apr 28 00:02 ../
-rw-r--r--  1 krinkle staff  640 Mar 17 18:34 .eslintrc.js
drwxr-xr-x  4 krinkle staff  128 Mar 17 18:34 .github/
-rw-r--r--  1 krinkle staff   37 Mar 17 18:34 .npmignore
-rw-r--r--  1 krinkle staff 8.3K Mar 17 18:34 CHANGELOG.md
-rw-r--r--  1 krinkle staff 1.1K Mar 17 18:34 LICENSE.md
-rw-r--r--  1 krinkle staff  757 Mar 17 18:34 README.md
drwxr-xr-x  3 krinkle staff   96 Mar 17 18:34 lib/
drwxr-xr-x  4 krinkle staff  128 Mar 17 18:34 node_modules/
-rw-r--r--  1 krinkle staff 252K Mar 17 18:34 package-lock.json
-rw-r--r--  1 krinkle staff 2.8K Mar 17 18:34 package.json
-rw-r--r--  1 krinkle staff   63 Mar 17 18:34 release.config.js
-rw-r--r--  1 krinkle staff 123K Mar 17 18:34 screenshot.png
drwxr-xr-x  4 krinkle staff  128 Mar 17 18:34 spec/
drwxr-xr-x  3 krinkle staff   96 Mar 17 18:34 styles/
```
</details>

<details><summary><code>cat ~/.atom/packages/minimap-highlight-selected/package.json</code></summary>

```
$ head package.json; tail package.json 
{
  "_from": "https://www.atom.io/api/packages/minimap-highlight-selected/versions/4.6.5/tarball",
  "_id": "minimap-highlight-selected@4.6.5",
  "_inBundle": false,
  "_integrity": "sha512-eppLh3r/FjetoBTXypOaQ5G5geZSnwj/+JeI0pExrPSN5cgSIQ5jJetVMWeUNrqDhOFQ7zSge5HvpAcvXIHWIg==",
  "_location": "/minimap-highlight-selected",
  "_phantomChildren": {},
  "_requested": {
    "type": "remote",
    "raw": "https://www.atom.io/api/packages/minimap-highlight-selected/versions/4.6.5/tarball",

…


  "repository": {
    "type": "git",
    "url": "git+https://github.com/atom-minimap/minimap-highlight-selected.git"
  },
  "scripts": {
    "lint": "eslint .",
    "test": "atom --test spec"
  },
  "version": "4.6.5"
}
```
</details>

<details><summary><code>tree -a ~/.atom/packages/minimap-highlight-selected/**</code></summary>

```
$ tree  -a
.
|-- .eslintrc.js
|-- .github
|   |-- dependabot.yml
|   `-- workflows
|       `-- CI.yml
|-- .npmignore
|-- CHANGELOG.md
|-- LICENSE.md
|-- README.md
|-- lib
|   `-- minimap-highlight-selected.js
|-- node_modules
|   |-- .bin
|   |   `-- atom-package-deps -> ../atom-package-deps/lib/bin.js
|   `-- atom-package-deps
|       |-- CHANGELOG.md
|       |-- LICENSE.md
|       |-- README.md
|       |-- lib
|       |   |-- bin.d.ts
|       |   |-- bin.js
|       |   |-- constants.d.ts
|       |   |-- helpers
|       |   |   |-- atom.d.ts
|       |   |   |-- index.d.ts
|       |   |   `-- node.d.ts
|       |   |-- index.d.ts
|       |   |-- index.js
|       |   |-- types.d.ts
|       |   `-- view
|       |       |-- atom.d.ts
|       |       |-- index.d.ts
|       |       `-- node.d.ts
|       `-- package.json
|-- package-lock.json
|-- package.json
|-- release.config.js
|-- screenshot.png
|-- spec
|   |-- minimap-highlight-selected-spec.js
|   `-- runner.js
`-- styles
    `-- minimap-highlight-selected.less

11 directories, 32 files
```
</details>

And the directory in full, in case it's of use (no modifications as far as I'm aware): [minimap-highlight-selected.tar.gz](https://github.com/atom-minimap/minimap-highlight-selected/files/6388181/minimap-highlight-selected.tar.gz)

I added a breakpoint here in the plugin:
```js
		debugger;
		require('atom-package-deps').install('minimap-highlight-selected')
```

From which I observed the following sequence:
1. The `atom-package-deps` module and its entry point get found and executed.
2. The `install()` function uses atom built-ins to find `minimap-highlight-selected` and determine what its dependencies are, which yields `[{"name":"minimap"}, {"name:"highlight-selected"}]`.
3. The `install()` function adds a directory property with a path to the already-installed dependency if it is indeed already installed. Otherwise, null. As expected, minimap has a directory, and highlight-selected does not.
4. The `install()` function reduces the list to those it "should" install. In other words, not having a directory yet, and not being "ignored". All good, the list is narrowed to `highlight-selected`.
5. We reach `confirmPackagesToInstall$2()`. This is where things get fuzzy to me. I'm not sure of what some of the variables here mean, or what their correct value would be. But, at the end of this function, pressing "Yes" results in the confirmation Promise being resolved with an empty array, and the UI reacting as if the user choose to cancel, which is incorrect. In more detail:
6.  The `confirmPackagesToInstall$2()` function is splitting dependencies by "grouped" and "ungrouped". I don't know what for, but it is determined based on whether an item is an array. Our item is `{"name:"highlight-selected","directory":null}`, so it gets categorised as "ungrouped".
7. The `confirmPackagesToInstall$2()` function sets `skipGroups` to `true`, because `groupedDependencies.length === 0`. However, as noted, the `"highlight-selected"` dependency you need, is under `ungroupedDependencies`.
8. After pressing "Yes", this `skipGroups` variable is used to decide to resolve the confirimation Promise with an empty array. Control is returned to the `install` function.
9. The `install()` function sees the resolved value via a variable named `choosenDependencies`, determins that it is empty, and does an early return, after which the prompt remains gone, and nothing else happens. The early return has a code comment saying "_Short-circuit if user interaction cancelled all_".

| Step 1 | Step 2 | Step 3 | Step 4
|--|--|--|--
| ![Screenshot 1](https://user-images.githubusercontent.com/156867/116327379-8d3ad500-a7be-11eb-800d-ce1daf274a31.png) | ![Screenshot 2](https://user-images.githubusercontent.com/156867/116327381-8dd36b80-a7be-11eb-8a96-516222aafb9e.png) | ![Screenshot 3](https://user-images.githubusercontent.com/156867/116327382-8dd36b80-a7be-11eb-82ba-a93704bf4a05.png) | ![Screenshot 4](https://user-images.githubusercontent.com/156867/116327383-8e6c0200-a7be-11eb-81ae-5bbe016a19fb.png)

| Step 5 | Step 6 | Step 7 | Step 9
|--|--|--|--
| ![Screenshot 5](https://user-images.githubusercontent.com/156867/116327384-8e6c0200-a7be-11eb-9dae-9c54ff815297.png) | ![Screenshot 6](https://user-images.githubusercontent.com/156867/116327385-8f049880-a7be-11eb-8f4c-e31b4eca52be.png) | ![Screenshot 7](https://user-images.githubusercontent.com/156867/116327386-8f049880-a7be-11eb-9409-9dc45efc58a3.png) | ![Screenshot 9](https://user-images.githubusercontent.com/156867/116327388-8f9d2f00-a7be-11eb-9c13-8a81fd489a5e.png)

**Comment by Krinkle** [comment]
Appears to have already been filed and fixed upstream at https://github.com/steelbrain/package-deps/pull/333.

I'm curious why it doesn't happen for you, though. What makes this dependency considered "grouped" for you?

**Comment by UziTech** [comment]
I think if you uninstall minimap-highlight-selected and reinstall it the updated version of atom-package-deps should be installed.

**Comment by Krinkle** [comment]
@UziTech I understand but there isn't a way in the interface to do that as there hasn't been a release. There's also a cache it seems, so it requires a restart in-between which might not be obvious to users.

The regression was introduced in package-deps v7.0 by commit https://github.com/steelbrain/package-deps/commit/09e0cf2afc410cf431847f5721dc4a96144fd6a9, which was released 28 Nov 2020 in minimap-highlight-selected v4.6.2 via commit https://github.com/atom-minimap/minimap-highlight-selected/commit/c349d21968cee637efb33c5691184f1356ef8ba5.

The last release, v4.6.5, was on 18 Jan. The fix was released in [package-deps v7.2.3](https://github.com/steelbrain/package-deps/releases/tag/v7.2.3) on 23 Mar. So, I would expect most users to be potentially affected like myself, unless they've last updated before 28 Nov 2020, and did not update to v4.6.5 until after 23 Mar 2021. On the other hand, it remains a mystery of course why highlight-selected went missing in the first place. That I don't know.

**Comment by UziTech** [comment]
The dependency for atom-package-deps is set to `^7 1.0` and APM uses npm to install the dependencies so version 7.2.3 will be installed for anyone who installs this package for the first time. So a new release won't help anyone unless they are in a strange situation like yours.

**Comment by UziTech** [comment]
Thanks for debugging this! :100:
